# Generated by Django 3.1.7 on 2021-03-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210313_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['joined']},
        ),
    ]
