# Generated by Django 3.1.7 on 2021-03-13 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210313_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
