# Generated by Django 3.1.7 on 2021-03-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210313_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giveaway',
            old_name='winners',
            new_name='num_winners',
        ),
    ]
