# Generated by Django 3.1.7 on 2021-03-14 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210314_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='api.giveaway')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giveaways_won', to='api.participant')),
            ],
            options={
                'unique_together': {('participant', 'giveaway')},
            },
        ),
    ]
